services:
  nginx_tsl:
    build:
      context: .
      dockerfile: ./requirements/Nginx/Dockerfile
    volumes:
      - ./wp_data:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env

  wordpress:
    build:
      context: .
      dockerfile: ./requirements/Wordpress/Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    restart: always
    env_file:
      - .env
    ports:
      - "9000"
  mariadb:
    build:
      context: .
      dockerfile: ./requirements/MariaDb/Dockerfile
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./src/wp_data
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./src/db_data



networks:
  network:
    driver: bridge