services:
  # nginx_tsl:
  #   build:
  #     context: .
  #     dockerfile: ./Nginx/Dockerfile
  #   volumes:
  #     - ./Nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  #     - ./Nginx/html:/usr/share/nginx/html
  #   ports:
  #     - "443:443"
  mariadb:
    build:
      context: .
      dockerfile: ./requirements/MariaDb/Dockerfile
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wp_data
  db_data:
    
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db_data



networks:
  network:
    driver: bridge